env:
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  indent: ["warn", 2, { "SwitchCase": 1 }]
  no-trailing-spaces: 0
  no-console: 1
  no-unreachable: 1
  eqeqeq: 2
  prefer-promise-reject-errors: 1
  require-await: 2
  wrap-iife: 2
  no-use-before-define: 2
  prefer-const: 1
  eol-last: 2
  linebreak-style: ["error", "unix"]
  no-irregular-whitespace: 2
  no-shadow: 2
  no-undef: 2
  no-unused-vars: 2
  no-var: 2
  semi: ["error", "always"]